version: "3.8"

services:
  db:
    image: mongo
    restart: always
    container_name: nsuf
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=abc123
    ports:
      - "27017:27017"